### ISSUE TITLE
Using the library for accessing a device connected via USB

### ISSUE THREAD

**Issue by rouvoy** [dhhagan/py-opc#15]
My OPC-N2 device is connected to my Raspberry Pi 2 using a USB adapter, and the current version of the library fails to connect to the device. Did you give a try to such settings?

**Comment by dhhagan** [comment]
That is correct. I assume you are using a SPI-USB adapter? The library is written to communicate directly over the Raspberry Pi's SPI interface only. You will need to connect the Pi to the OPC-N2 as shown in the documents, or write SPI-USB drivers for the original Alphasense code. Let me know if you have any more questions.

**Comment by MarceloYung** [comment]
How can I write SPI-USB drivers for the original Alphasense code?

**Comment by DancingQuanta** [comment]
What SPI-USB devices are you trying to use with alphasense?

**Comment by dhhagan** [comment]
@MarceloYung And what do you mean by the 'original Alphasense code"? The only software they offer is a windows-based GUI; is this what you're referring to?

**Comment by MarceloYung** [comment]
I am using the py-opc library for an OPC-N2 sensor, and it doesn't work. And I am connecting the raspberry PI 2 and the OPC-N2 with a SPI-USB adapter. The connection doesn't start using the library.
I tried the sensor in Windows application (provided by Alphasense) and it worked correctly.
I was reading this page and you said that the OPC-N2 and that the library is written to communicate directly over the Raspberry Pi's SPI interface only, and I am asking how to comunnicate when I use an USB adapter, as I show in the attached image file.
The version of my OPC-N2 is v18.2. 
Thanks for your help!!
![20160924_073603](https://cloud.githubusercontent.com/assets/22395840/18808488/c2daacae-8229-11e6-8b5d-c0001788d1e8.jpg)

**Comment by DancingQuanta** [comment]
Ah, I wrote such a driver for that adapter, that adapter is called USB-ISS.
My driver is a python module at https://github.com/DancingQuanta/pyusbiss.
You have to download it and install using the instructions on my README.
Please open an issue over there if you have any issues.
I also have an example script that I will upload soon.

**Comment by DancingQuanta** [comment]
@MarceloYung I have uploaded the example script here https://github.com/DancingQuanta/pyusbopc.
Please open an issue over there if you have any problems

**Comment by MarceloYung** [comment]
Thanks very much, my project is working!!

**Comment by DancingQuanta** [comment]
Fantastic
