### ISSUE TITLE
Problems installing py-opc

### ISSUE THREAD

**Issue by beleme** [dhhagan/py-opc#43]
I  have a problem because when i write the comand pip install py-opc  I get this error 

error: could not create úsr/local/lib/python2.7/dist-packages/opc´: Permission denied

how can I solve it?

**Comment by dhhagan** [comment]
@beleme Sounds like you are having a permissions problem.
Try `sudo pip install py-opc`

**Comment by beleme** [comment]
thanks!! @dhhagan 

problem solved
 why I have that type of problem ?
how can I solve it so that it does not happen again?

**Comment by dhhagan** [comment]
@beleme It has to do with how you've set your permissions. Google will provide a much better answer than I can..
