### ISSUE TITLE
Create page for mentions/citations

### ISSUE THREAD

**Issue by dhhagan** [dhhagan/py-opc#50]
Allow people/orgs using the code to list themselves (if desired) so we can see who all is using this codebase!

**Comment by DancingQuanta** [comment]
I have used this py-opc library for my summer placement at University of Leeds at Earth and Environment dept. I was studying the difference between customer-grade, industry-grade and scientific-grade aerosol sensors where an alphasense-N2 was evaluated.

**Comment by dhhagan** [comment]
Hey @DancingQuanta, thanks for the update! I am considering submitting this repository to the Journal of Open Source Software, which means I would be listing you as a co-author since you are a contributor. Is that okay? If so, could you send me an email at dhagan@mit.edu with your most up-to-date affiliation/university/employer?
