### ISSUE TITLE
ERROR: opc: Could not parse the firmware version from

### ISSUE THREAD

**Issue by mc13756** [dhhagan/py-opc#76]
I tried to run the code and I got the following errors:

ERROR:opc:Could not parse the fimrware version from ????????????????????????????????????????????????????????????
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/opc/__init__.py", line 77, in __init__
    self.firmware['version'] = int(re.findall("\d{3}", infostring)[-1])
IndexError: list index out of range

IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Desktop/opc_test_3.py", line 31, in <module>
    alpha = OPCN2(spi)
  File "/home/pi/.local/lib/python3.5/site-packages/opc/__init__.py", line 293, in __init__
    super(OPCN2, self).__init__(spi_connection, model='N2', **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/opc/__init__.py", line 71, in __init__
    raise FirmwareVersionError(msg)
opc.exceptions.FirmwareVersionError: 
                            Your firmware version could not be automatically detected. This is usually caused by bad wiring or a poor power supply. If niether of these are likely candidates, please open an issue on the GitHub repository at https://github.com/dhhagan/py-opc/issues/new. Another option would be to
                            increase the max_cnxn_retries variable if you feel the serial communication is being held up for some reason.
 Can you please help me solve this? I have no idea where these errors come from

**Comment by dhhagan** [comment]
Hi @mc13756 The error comes from not being able to correctly parse the firmware version of the OPC. Often, this is caused by a wiring issue, power issue, or sometimes a code issue. Can you please let us know which version of the software you are using (`opc.__version__`) and post the code you used to get to this point?

**Comment by dhhagan** [comment]
Thanks for that information. Which version of the `py-opc` library are you using? You can get it by issuing the command `opc.__version__`; you can also get it by running `$pip list` at the terminal and finding the version number of the package.

**Comment by mc13756** [comment]
I am using the library py-opc (1.6.0)

**Comment by dhhagan** [comment]
Thanks. How is it wired up? I assume you are using the GPIO pins? How is it being powered?

**Comment by mc13756** [comment]
Yes, I am using the GPIO pins. I give 4.6 V through an external battery. I've already checked the wiring connection and it's working fine.

**Comment by dhhagan** [comment]
Ahh okay. Have you verified the OPC-N2 will work with 4.6V? I believe it requires at least 4.8VDC and > 250 mA. You could test it by simply plugging the battery into the micro-USB slot on the OPC; it will start up by itself after a minute and log data internally. You can then grab that data via the micro-USB slot and see if it makes sense.

**Comment by mc13756** [comment]
I increased the voltage to 4.9 V with the same result. Also, I tried the following code too, in order to get the results analytically:

https://gist.github.com/dhhagan/bfb17459f0067a120f09?signup=true

Sometimes the code starts compiling and I get an error at line 83 and sometimes I have the same result as the previous code. 
Error: opc: Firmware version is invalid for this device.

**Comment by dhhagan** [comment]
Hmm. Can you draw the wiring diagram. It's fairly easy to mix up MISO and MOSI, so I'd like to rule that out..

**Comment by mc13756** [comment]
![37278118_10217657498454997_2256412015855665152_n](https://user-images.githubusercontent.com/41290765/42801808-884e96ca-89a9-11e8-8ade-3fd161245f32.jpg)

**Comment by metallicano** [comment]
how can i now what firmaware version am using?

**Comment by dhhagan** [comment]
Hi @metallicano; are you able to connect to the device? If so, you can use either `read_information_string()` or `read_firmware_version()`.

**Comment by dhhagan** [comment]
@mc13756 This seems like a wiring issue (hopefully an easy fix!). According to this [diagram][1], you should have the following:

  * SCK -> GPIO 14, Pin 23
  * SDO/MISO -> GPIO 13, Pin 21
  * SDI/MOSI -> GPIO 12, Pin 19
  * /SS -> GPIO 10 or 11, Pins 24, 26

If you haven't already seen this, the instructions can be found [here][2].

Let me know if this doesn't work.

[1]: http://pi4j.com/pins/model-3b-rev1.html
[2]: http://py-opc.readthedocs.io/en/latest/#connecting-via-gpio

**Comment by mc13756** [comment]
I've checked the wiring and is just like you mentioned above.  I run the extended version of code
https://gist.github.com/dhhagan/bfb17459f0067a120f09?signup=true
and I got the following error. 

ERROR:opc:Firmware version is invalid for this device.
Traceback (most recent call last):
  File "/home/pi/Desktop/opc_test_3.py", line 31, in <module>
    alpha = OPCN2(spi)
  File "/home/pi/.local/lib/python3.5/site-packages/opc/__init__.py", line 301, in __init__
    raise FirmwareVersionError("Your firmware is not yet supported. Only versions 14-18 are currently supported.")
opc.exceptions.FirmwareVersionError: Your firmware is not yet supported. Only versions 14-18 are currently supported

Also, when I tried to install py-opc by typing:    pip install py-opc [--upgrade]   in a terminal I got:
"Invalid requirement: '[--upgrade]'
so I've installed it by typing only: pip install py-opc

**Comment by dhhagan** [comment]
@mc13756 Try `pip install py-opc --upgrade` - the brackets are just to indicate it is optional

**Comment by mc13756** [comment]
ok. thank you.
It seems like OPC works randomly.  Sometimes I got the following error:

ERROR:opc:Firmware version is invalid for this device.
Traceback (most recent call last):
  File "/home/pi/Desktop/opc_test_3.py", line 31, in <module>
    alpha = OPCN2(spi)
  File "/home/pi/.local/lib/python3.5/site-packages/opc/__init__.py", line 301, in __init__
    raise FirmwareVersionError("Your firmware is not yet supported. Only versions 14-18 are currently supported.")
opc.exceptions.FirmwareVersionError: Your firmware is not yet supported. Only versions 14-18 are currently supported

Sometimes the code runs normally and I got numbers every 10 seconds, and some other times it looks like it runs ok but I got only zeros. In this case the OPC's fan isn't working and I get false on turning ON or OFF the opc.

Turning on the opc
ON: False

or

Turning off the opc
OFF: False

**Comment by dhhagan** [comment]
@mc13756 Interesting - the script your using is pretty outdated (from 2015, I think). I would take a look at the most up-to-date docs for reference. When did you buy the OPC and do you have the SPI-USB connector for debugging purposes? Your OPC is most likely v18.2, but I can't be sure..

**Comment by mc13756** [comment]
I think we bought the OPC on 2015 and our version is 18.2. Yes, I have the SPI-USB connentor

**Comment by metallicano** [comment]
hi , the problem persist , but in the end of the text i have this : your firmware is not supported :C

**Comment by metallicano** [comment]
now the code runs but sometimes XD,

**Comment by dhhagan** [comment]
@metallicano Can you post the code and wiring you're using?

**Comment by metallicano** [comment]
import spidev
import opc
from time import sleep

spi = spidev.SpiDev()
spi.open(0, 0)
spi.mode = 1
spi.max_speed_hz = 500000

alphasense = opc.OPCN2(spi)

# Turn the opc ON
alphasense.on()

sleep(1)

# Read the information string
print (alphasense.read_info_string())

# Read the histogram
print (alphasense.histogram())

# Turn the opc OFF
alphasense.off()



thw wiring is the same : 
SCK -> GPIO 14, Pin 23
SDO/MISO -> GPIO 13, Pin 21
SDI/MOSI -> GPIO 12, Pin 19
/SS -> GPIO 10 or 11, Pins 24, 26

**Comment by metallicano** [comment]
import spidev
import opc
from time import sleep

spi = spidev.SpiDev()
spi.open(0, 0)
spi.mode = 1
spi.max_speed_hz = 500000

alphasense = opc.OPCN2(spi)

# Turn the opc ON
alphasense.on()

sleep(1)

# Read the information string
print (alphasense.read_info_string())

# Read the histogram
print (alphasense.histogram())

# Turn the opc OFF
alphasense.off()

**Comment by metallicano** [comment]
import spidev
import opc
from time import sleep

spi = spidev.SpiDev()
spi.open(0, 0)
spi.mode = 1
spi.max_speed_hz = 500000

alphasense = opc.OPCN2(spi)

# Turn the opc ON
alphasense.on()

sleep(1)

# Read the information string
print (alphasense.read_info_string())

# Read the histogram
print (alphasense.histogram())

# Turn the opc OFF
alphasense.off()

**Comment by metallicano** [comment]
import spidev
import opc
from time import sleep

spi = spidev.SpiDev()
spi.open(0, 0)
spi.mode = 1
spi.max_speed_hz = 500000

alphasense = opc.OPCN2(spi)
alphasense.on()
sleep(1)
print (alphasense.read_info_string())
print (alphasense.histogram())
alphasense.off()

**Comment by metallicano** [comment]
the wiring is the same : 
SCK -> GPIO 14, Pin 23
SDO/MISO -> GPIO 13, Pin 21
SDI/MOSI -> GPIO 12, Pin 19
/SS -> GPIO 10 or 11, Pins 24, 26

**Comment by metallicano** [comment]
hi , problem solved , thanks for all 💯

**Comment by DancingQuanta** [comment]
The decimals could be an average. Can you show the data you are getting please?

**Comment by dhhagan** [comment]
Hey @mc13756 The reason you are getting decimals is because the default argument for `number_concentration` is `True` (read more about it in the [docs](http://py-opc.readthedocs.io/en/latest/#opc.OPCN2.histogram)). Thus, the number concentration in units of #/cc is being returned rather than the raw count. If you want the raw count, simply set `number_concentration=False`.

**Comment by mc13756** [comment]
How can I get access to change the number_concentration to False?

**Comment by dhhagan** [comment]
@mc13756 It's just an argument to `opc.histogram()`. So if you wanted to return the values as a raw histogram, you would do `opc.histogram(False)` or `opc.histogram(number_concentration=False)`.

**Comment by mc13756** [comment]
I changed the argument to False and everything looks to work normally. 

Thank you very much!!!

**Comment by dhhagan** [comment]
Good to hear, @mc13756: just be aware that the number you are seeing is the total number of particles in each bin since the last time you called either `pm()` or `histogram()`. In doing the conversion to #/cc, I was accounting for the sampling time and flow rate.
