### ISSUE TITLE
conect the opc to other pins

### ISSUE THREAD

**Issue by metallicano** [dhhagan/py-opc#79]
hi , i need to coenct two opc to my raspberry, i saw other pins for the spi comunications 

gpio 21 = sclk
gpio19 = miso
gpio20 = mosi
gpio 7=ce1

when i try to conect mi opc to that pins and run the code y have de firmware version problem,so how i can use that gpio pins ?

**Comment by dhhagan** [comment]
Which version of the Raspberry Pi are you using? Or is it another device?

**Comment by metallicano** [comment]
pi zero w , i find this in internet:
https://raspberrypi.stackexchange.com/questions/83610/gpio-pinout-orientation-raspberypi-zero-w
